

# WIG20
wig20_2019 = {
    'ALR': 'ALIOR',
    'CCC': 'CCC',
    'CDR': 'CDPROJEKT',
    'CPS': 'CYFRPLSAT',
    'DNP': 'DINOPL',
    'JSW': 'JSW',
    'KGH': 'KGHM',
    'LPP': 'LPP',
    'LTS': 'LOTOS',
    'MBK': 'MBANK',
    'OPL': 'ORANGEPL',
    'PEO': 'PEKAO',
    'PGE': 'PGE',
    'PGN': 'PGNIG',
    'PKN': 'PKNORLEN',
    'PKO': 'PKOBP',
    'PLY': 'PLAY',
    'PZU': 'PZU',
    'SPL': 'SANPL',
    'TPE': 'TAURONPE',
}

wig20 = {
    'ALE': 'ALLEGRO',
    'ALR': 'ALIOR',
    'CCC': 'CCC',
    'CDR': 'CDPROJEKT',
    'CPS': 'CYFRPLSAT',
    'DNP': 'DINOPL',
    'JSW': 'JSW',
    'KGH': 'KGHM',
    'LPP': 'LPP',
    'LTS': 'LOTOS',
    'OPL': 'ORANGEPL',
    'PEO': 'PEKAO',
    'PGE': 'PGE',
    'PGN': 'PGNIG',
    'PKN': 'PKNORLEN',
    'PKO': 'PKOBP',
    'PLY': 'PLAY',
    'PZU': 'PZU',
    'SPL': 'SANPL',
    'TPE': 'TAURONPE',
}


# mWIG40
mwig40 = {
    '11B':  '11BIT',
    'ACP':  'ASSECOPOL',
    'AMC':  'AMICA',
    'ASE':  'ASSECOSEE',
    'ATT':  'GRUPAAZOTY',
    'BDX':  'BUDIMEX',
    'BFT':  'BENEFIT',
    'BHW':  'HANDLOWY',
    'BNP':  'BNPPPL',
    'CAR':  'INTERCARS',
    'CIE':  'CIECH',
    'CLN':  'CLNPHARMA',
    'CMR':  'COMARCH',
    'DOM':  'DOMDEV',
    'DVL':  'DEVELIA',
    'EAT':  'AMREST',
    'ECH':  'ECHO',
    'ENA':  'ENEA',
    'ENG':  'ENERGA',
    'EUR':  'EUROCASH',
    'FMF':  'FAMUR',
    'FTE':  'FORTE',
    'GPW':  'GPW',
    'GTC':  'GTC',
    'GTN':  'GETIN',
    'ING':  'INGBSK',
    'KER':  'KERNEL',
    'KRU':  'KRUK',
    'KTY':  'KETY',
    'LVC':  'LIVECHAT',
    'LWB':  'BOGDANKA',
    'MAB':  'MABION',
    'MIL':  'MILLENNIUM',
    'NEU':  'NEUCA',
    'PKP':  'PKPCARGO',
    'PLW':  'PLAYWAY',
    'STP':  'STALPROD',
    'TEN':  'TSGAMES',
    'VRG':  'VRG',
    'WPL':  'WIRTUALNA',
}
